.travis.yml
hack/verify-all.sh
pkg/smb/smb_common_windows.go

test: fix travis error
add windows build test
/kind test
test: fix travis config
Fixes #
```
none
```

test: fix travis config

---

.travis.yml

/kind test
test: add code coverage
Fixes #
```
none
```

test: add code coverage

---

.travis.yml
Makefile
deploy/example/e2e_usage.md
deploy/example/windows/README.md
deploy/install-driver.sh
deploy/uninstall-driver.sh
docs/csi-dev.md
docs/install-csi-driver-master.md
go.mod
pkg/smb/smb.go
pkg/smb/smb_common_windows.go
pkg/smbplugin/main.go
test/sanity/sanity_test.go
test/utils/credentials/credentials.go

/kind cleanup
chore: repo rename
Fixes #
```
none
```

chore: repo rename

---

README.md

>
> /kind bug
> /kind design
> /kind test
> /kind flake
Link is broken
Fixes #
```
none
```

README:Fix broken link

---

pkg/smb/nodeserver.go
pkg/smb/nodeserver_test.go
pkg/smb/smb_test.go

>
> /kind bug
> /kind design
> /kind test
> /kind flake
Fixes #7 
A new test file has been created. The current test is specific to this Fix.
I will try and add a complete test file in another PR.
```
Fixes password which get exposed in logs.
```

Fix username and password exposed in logs

---

.github/workflows/go.yml

/kind test
test: add test coverage workflow
Fixes #
```
none
```

test: add test coverage workflow

---

hack/verify-all.sh
pkg/smb/nodeserver.go

/kind test
test: Enable golint check
Fixes #
```
none
```

test: Enable golint check in travis

---

pkg/csi-common/controllerserver-default_test.go
pkg/csi-common/driver_test.go
pkg/csi-common/utils_test.go
pkg/smb/controllerserver_test.go
pkg/smb/identityserver_test.go
pkg/smb/version_test.go

>
> /kind bug
> /kind design
> /kind flake
/kind test
Fixes #
```
Tests: Add Tests for csi-common and smb
```

Tests: Add Tests for csi-common and smb

---

.github/PULL_REQUEST_TEMPLATE.md
README.md
deploy/csi-smb-node-windows.yaml
deploy/csi-smb-node.yaml
docs/csi-dev.md

doc: switch to use mcr image

---

README.md
deploy/example/windows/deployment.yaml
deploy/v0.1.0/crd-csi-node-info.yaml
deploy/v0.1.0/csi-smb-driver.yaml
deploy/v0.1.0/csi-smb-node-windows.yaml
deploy/v0.1.0/csi-smb-node.yaml
docs/install-csi-driver-v0.1.0.md
docs/install-smb-csi-driver.md

doc: cut v0.1.0 release
Fixes #
```
doc: cut v0.1.0 release
```

doc: cut v0.1.0 release

---

pkg/smbplugin/Dockerfile

>
> /kind bug
> /kind design
> /kind test
> /kind flake
/kind feature
Updates base image with debian-base which is more secure
Fixes #19 
```
Docker: Update base image with debian-base
```

Docker: Update base image with debian-base

---

pkg/smb/nodeserver.go
pkg/smb/smb_common_linux.go
pkg/smb/smb_common_windows.go

/kind feature
feat: windows mount issue
Fixes #
```
support windows mount
```

feat: windows mount issue

---

deploy/csi-smb-node-windows.yaml
deploy/csi-smb-node.yaml
deploy/example/e2e_usage.md
deploy/example/windows/README.md
deploy/install-driver.sh
docs/install-csi-driver-master.md
pkg/smb/nodeserver.go
pkg/smb/smb_common_linux.go
pkg/smb/smb_common_windows.go

doc: change Windows docs
Fixes #
```
none
```

doc: change Windows docs

---

.travis.yml
Makefile
test/integration/run-test.sh

/kind test
Fixes #29 
```
none
```

test: enable integration test

---

pkg/smb/nodeserver.go
pkg/smb/smb_common_linux.go
pkg/smb/smb_common_windows.go

/kind bug
Original `k8s.io/utils/mount` is insecure, when there is mount failure, it would log all mount options which may contain password, this PR would use `MountSensitive` func instead.
Fixes #
```
fix: use MountSensitive to prevent password logging leak
```

fix: use MountSensitive to prevent password logging leak

---

pkg/smb/nodeserver.go

/kind bug
fix: Domain is not properly parameterized
Fixes #39
cc @gabriel-stan
```
none
```

fix: Domain is not properly parameterized

---

.travis.yml
test/integration/README.md
test/integration/run-test.sh

/kind test
test: refine integration test and add docs
Fixes #
```
none
```

test: refine integration test and add docs

---

Makefile

/kind feature
chore: fix Makefile
Fixes #
```
none
```

chore: fix Makefile

---

deploy/example/smb-provisioner/README.md
deploy/example/smb-provisioner/smb-server-deployment.yaml
hack/verify-yamllint.sh

/kind feature
Fixes #36 
```
none
```

feat: Write a samba server kubernetes deployment

---

pkg/csi-common/controllerserver-default_test.go
pkg/csi-common/server.go
pkg/csi-common/server_test.go
pkg/csi-common/utils.go
pkg/mounter/safe_mounter_unix_test.go
pkg/smb/controllerserver_test.go
pkg/smb/nodeserver_test.go
pkg/smb/smb.go
pkg/smb/smb_test.go
pkg/smbplugin/main.go

This commit adds unit tests for csi-common,
mounter and smb.
A testMode parameter has been introduced in
server to enable running of unit tests.
Unit tests for unimplemented methods are also
added.
>
> /kind bug
> /kind design
> /kind flake
/kind test
Fixes #
```
test: Add unit tests
```

test: Add unit tests

---

README.md
deploy/example/e2e_usage.md
deploy/example/smb-provisioner/README.md
deploy/example/smb-provisioner/pv-smb-csi.yaml
deploy/example/smb-provisioner/smb-server.yaml

doc: refine smb-provisioner doc
Fixes #
cc @Sakuralbj 
```
none
```

doc: refine smb-provisioner doc

---

deploy/csi-smb-node-windows.yaml
deploy/csi-smb-node.yaml
deploy/install-driver.sh

/kind bug
fix: installation issue
Fixes #
```
none
```

fix: installation issue

---

pkg/smb/fake_mounter.go
pkg/smb/fake_mounter_test.go
pkg/smb/nodeserver.go
pkg/smb/nodeserver_test.go

This commit adds unit test for nodeserver.
A fake mounter is also added to support the
unit tests.
Redundant checks for target path in Publish
Volume has been removed. A typo is also
fixed in nodeserver.
>
> /kind bug
> /kind design
> /kind flake
/kind test
Adds unit tests for nodeserver
Fixes #
Multiple checks for target path has been removed from NodePublishVolume has …

test: Add unit test for nodeserver

---

deploy/example/smb-provisioner/smb-server.yaml
go.mod
pkg/csi-common/controllerserver-default.go
pkg/csi-common/driver.go
pkg/csi-common/identityserver-default.go
pkg/csi-common/nodeserver-default.go
pkg/csi-common/server.go
pkg/csi-common/utils.go
pkg/csi-common/utils_test.go
pkg/mounter/safe_mounter_windows.go
pkg/smb/controllerserver.go
pkg/smb/identityserver.go
pkg/smb/nodeserver.go
pkg/smb/smb.go
pkg/smb/smb_common_windows.go
pkg/smbplugin/main.go
vendor/modules.txt

/kind cleanup
chore: move to klog/v2
Fixes #
```
none
```

chore: move to klog/v2

---

go.mod
go.sum
pkg/smb/controllerserver.go
pkg/smb/controllerserver_test.go
vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go
vendor/modules.txt

/kind feature
chore: move to csi-v1.3.0
Fixes #
```
chore: move to csi-v1.3.0
```

chore: move to csi-v1.3.0

---

Makefile
hack/release-image.sh

/kind feature
add hack/release-image.sh
Fixes #
```
none
```

chore: add hack/release-image.sh

---

test/integration/run-test.sh

Integration test now uses servercontainers/samba
docker image.
>
> /kind bug
> /kind design
> /kind test
> /kind flake
/kind feature
Fixes #
```
test: Update samba docker image
```

test: Update samba docker image

---

deploy/example/e2e_usage.md
deploy/example/smb-provisioner/README.md
deploy/example/smb-provisioner/smb-server-azuredisk.yaml
hack/release-image.sh

doc: update samba server doc
Fixes #
```
none
```

doc: update samba server doc

---

hack/verify-all.sh

/kind test
test: add helm chart verification
Fixes #
```
none
```

test: add helm chart verification

---

hack/verify-gomod.sh

/kind test
test: add verify-gomod.sh
Fixes #
```
none
```

test: add verify-gomod.sh

---

.travis.yml
Makefile
hack/verify-golint.sh

>
> /kind bug
> /kind design
> /kind test
> /kind flake
only blocker for https://github.com/kubernetes/test-infra/pull/18403.
/assign @andyzhangx 
Fixes #
```
none
```

build: use docker buildx to build Linux and Windows images

---

deploy/example/smb-provisioner/smb-server.yaml
pkg/smb/nodeserver.go

/kind bug
This PR uses `wait.PollImmediate` instead of `wait.Poll` function to initial delay(5s) when mounting smb file
Fixes #
```
fix: initial delay(5s) when mounting smb file
```

fix: initial delay(5s) when mounting smb file

---

pkg/smb/nodeserver.go

/kind bug
fix: password logging issue in Windows node driver logs
Fixes #
```
fix: password logging issue in Windows node driver logs
```

fix: password logging issue in Windows node driver logs

---

Makefile
pkg/smb/nodeserver.go

/kind bug
fix: mkdir error in NodePublishVolume
Fixes #
```
fix: mkdir error in NodePublishVolume
```

fix: mkdir error in NodePublishVolume

---

deploy/example/deployment.yaml
deploy/example/smb-provisioner/smb-server-azuredisk.yaml
deploy/example/windows/statefulset.yaml
pkg/smb/nodeserver.go

doc: fix windows example
Fixes #
```
none
```

doc: fix windows example

---

test/e2e/dynamic_provisioning_test.go
test/e2e/manifests/linux.json
test/e2e/suite_test.go

/kind test
test: add e2e test manifest file
Fixes #
```
none
```

test: add e2e test manifest file

---

Makefile
charts/README.md
charts/index.yaml
charts/latest/csi-driver-smb/templates/csi-smb-controller.yaml
test/e2e/suite_test.go

/kind test
test: Install SMB provisioner in e2e test
Fixes #
```
none
```

test: Install SMB provisioner in e2e test

---

charts/latest/csi-driver-smb/templates/csi-smb-controller.yaml
charts/latest/csi-driver-smb/templates/csi-smb-node-windows.yaml
charts/latest/csi-driver-smb/templates/csi-smb-node.yaml
deploy/csi-smb-controller.yaml
deploy/csi-smb-node-windows.yaml
deploy/csi-smb-node.yaml
test/e2e/testsuites/testsuites.go

/kind bug
/kind flake
1. Set the reasonable CPU and Memory.
- Reduce limit of azurefile container CPU and Memory to one fifth.
- Reduce limit of sidecar containers CPU and Memory to one tenth.
2. Ignore the NotFound error.
Fixes #
```
none
```

chore: reduce the CPU/Memory and ignore the NotFound error

---

test/e2e/dynamic_provisioning_test.go
test/e2e/testsuites/dynamically_provisioned_collocated_pod_tester.go

/kind test
test: add multi pods e2e test
Fixes #
```
none
```

test: add multi pods e2e test

---

test/e2e/dynamic_provisioning_test.go
test/e2e/testsuites/dynamically_provisioned_read_only_volume_tester.go

/kind test
test: add read-only e2e test
Fixes #
```
none
```

test: add read-only e2e test

---

charts/latest/csi-driver-smb/templates/csi-smb-controller.yaml
charts/latest/csi-driver-smb/templates/csi-smb-node-windows.yaml
charts/latest/csi-driver-smb/templates/csi-smb-node.yaml
deploy/csi-smb-controller.yaml
deploy/csi-smb-node-windows.yaml
deploy/csi-smb-node.yaml

/kind cleanup
chore: port num change
Fixes #
```
chore: port num change
```

chore: port num change

---

Makefile
deploy/example/smb-provisioner/smb-server-lb.yaml
deploy/example/smb-provisioner/smb-server.yaml
pkg/smb/nodeserver.go
test/e2e/dynamic_provisioning_test.go
test/e2e/suite_test.go
test/e2e/testsuites/specs.go
test/utils/get_smb_svc_public_ip.sh
test/utils/smb_log.sh

/kind test
test: fix windows e2e test failures
Fixes #
```
none
```

test: fix windows e2e test failures

---

test/e2e/dynamic_provisioning_test.go
test/e2e/suite_test.go

/kind test
test: fix windows e2e test failure
Fixes #
```
none
```

test: fix windows e2e test failure

---

pkg/smb/nodeserver.go
pkg/smb/smb_common_darwin.go
pkg/smb/smb_common_linux.go
pkg/smb/smb_common_windows.go
test/e2e/dynamic_provisioning_test.go
test/e2e/suite_test.go

/kind test
test: add createSubDir e2e test
Fixes #
```
none
```

test: add createSubDir e2e test

---

test/e2e/dynamic_provisioning_test.go
test/e2e/testsuites/dynamically_provisioned_delete_pod_tester.go

/kind test
test: add delete pod e2e test
Fixes #
```
none
```

test: add delete pod e2e test

---

test/e2e/dynamic_provisioning_test.go
test/e2e/testsuites/dynamically_provisioned_pod_with_multiple_pv.go
test/e2e/testsuites/dynamically_provisioned_reclaim_policy_tester.go
test/e2e/testsuites/specs.go

/kind test
test: add reclaim policy e2e test
Fixes #
```
none
```

test: add reclaim policy e2e test

---

test/sanity/run-test.sh

/kind test
test: enable more sanity tests
Fixes #
```
Ran 28 of 70 Specs in 0.210 seconds
SUCCESS! -- 28 Passed | 0 Failed | 0 Pending | 42 Skipped
```
```
none
```

test: enable more sanity tests

---

charts/README.md
charts/latest/csi-driver-smb/templates/_helpers.tpl
charts/latest/csi-driver-smb/templates/csi-smb-controller.yaml
charts/latest/csi-driver-smb/templates/csi-smb-node-windows.yaml
charts/latest/csi-driver-smb/templates/csi-smb-node.yaml

/kind feature
Addressing [494](https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/494)
Fixes #
```
feat: Add imagePullSecrets in Helm chart for secret used to pull Docker images
```

feat: Add imagePullSecrets in Helm chart for secret used to pull Docker images

---

test/e2e/manifest/linux.json
test/utils/smb_log.sh

/kind cleanup
test: run e2e test on containerd
Fixes #
```
none
```

test: run e2e test on containerd

---

.github/PULL_REQUEST_TEMPLATE.md

test: fix PULL_REQUEST_TEMPLATE
Fixes #
```
none
```

test: fix PULL_REQUEST_TEMPLATE

---

Makefile
charts/README.md
charts/latest/csi-driver-smb/templates/csi-smb-controller.yaml
charts/latest/csi-driver-smb/templates/csi-smb-node-windows.yaml
charts/latest/csi-driver-smb/templates/csi-smb-node.yaml
charts/latest/csi-driver-smb/values.yaml
deploy/csi-smb-controller.yaml
deploy/csi-smb-node-windows.yaml
deploy/csi-smb-node.yaml
deploy/example/metrics/README.md
deploy/example/metrics/csi-smb-controller-svc.yaml
hack/verify-yamllint.sh
pkg/smbplugin/main.go
test/e2e/suite_test.go
test/utils/smb_log.sh

/kind test
test: add metrics logging in e2e test
Fixes #
```
none
```

test: add metrics logging in e2e test

---

pkg/smbplugin/Dockerfile

/kind bug
Update debian base image to v2.1.3 to address CVEs.
Fixes #
```
fix: Update debian base image to v2.1.3
```

fix: Update debian base image to v2.1.3

---

test/e2e/manifest/linux.json
test/e2e/manifest/windows.json

test: add csi-proxy-v0.1.0 config
Fixes #
```
none
```

test: add csi-proxy-v0.1.0 test config

---

Makefile
deploy/example/deployment.yaml
deploy/example/nginx-pod-smb.yaml
deploy/example/statefulset.yaml
hack/verify-golint.sh
test/e2e/suite_test.go
test/utils/smb_log.sh

test: switch to use mcr nginx image
Fixes #
```
test: switch to use mcr nginx image
```

test: switch to use mcr nginx image

---

.github/workflows/windows.yml
pkg/smb/fake_mounter.go
pkg/smb/nodeserver_test.go
pkg/smb/smb_test.go
test/utils/testutil/testutil.go

/kind test
test: enable windows unit tests with `csi-proxy.exe` 
https://github.com/kubernetes-csi/csi-driver-smb/issues/121
https://github.com/kubernetes-csi/csi-driver-smb/issues/109
Fixes #
```
none
```

test: enable windows unit tests with `csi-proxy.exe` 

---

.github/workflows/darwin.yaml
.github/workflows/ubuntu.yml
.github/workflows/windows.yml
charts/latest/csi-driver-smb/templates/csi-smb-controller.yaml
charts/latest/csi-driver-smb/templates/csi-smb-node.yaml
deploy/csi-smb-controller.yaml
deploy/csi-smb-node.yaml
pkg/smbplugin/Dockerfile
pkg/smbplugin/dev.Dockerfile

/kind bug
fix: create nonroot user in Dockerfile
Fixes #
```
fix: create nonroot user in Dockerfile
```

fix: create nonroot user in Dockerfile

---

charts/latest/csi-driver-smb/templates/csi-smb-node.yaml
deploy/csi-smb-node.yaml

/kind bug
fix: cifs mount broken after driver restart
Fixes #130
```
fix: cifs mount broken after driver restart
```

fix: cifs mount broken after driver restart

---

test/integration/run-test.sh

test: fix integration test failure
latest https://hub.docker.com/r/servercontainers/samba/tags image is broken in integration test
Fixes #
```
none
```

test: fix integration test failure

---

Makefile
docs/csi-dev.md
hack/release-image.sh
pkg/smbplugin/Windows.Dockerfile

Signed-off-by: Ernest Wong <chuwon@microsoft.com>
/assign @andyzhangx 
```
none
```

image: support multi OS versions for Windows images

---

charts/latest/csi-driver-smb/templates/csi-smb-controller.yaml
charts/latest/csi-driver-smb/templates/csi-smb-node.yaml
charts/latest/csi-driver-smb/values.yaml
deploy/csi-smb-controller.yaml
deploy/csi-smb-node.yaml

/kind bug
Replace livenessprobe flag --connection-timeout with --probe-timeout.
Update the livenessprobe version from v1.1.0 to v2.0.0.
Update helm charts.
Fixes #
```
none
```

fix: update livenessprobe version from v1.1.0 to v2.0.0

---

charts/latest/csi-driver-smb/templates/csi-smb-controller.yaml
charts/latest/csi-driver-smb/values.yaml
deploy/csi-smb-controller.yaml
deploy/csi-smb-node.yaml

/kind cleanup
charts: Fix image repo, version and flag
Fixes #145
```
Fix image repo, version and flag to support ARM64
```

Fix image repo, version and flag to support ARM64

---

docs/install-csi-driver-v0.4.0.md

quick addition to also check windows labels

watch windows pods

---

pkg/mounter/safe_mounter_windows.go

/kind bug
Fix an access violation issue
Fixes # https://github.com/kubernetes-csi/csi-driver-smb/issues/150
```
none
```

Check isExistsResponse for nil before accessing Exists field

---

.github/workflows/static.yaml

Due to a security vulnerability in GH Actions runner (https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/), `set-env` and `add-path` commands have been disabled, which caused `golangci-linter-action` to fail in GH Actions. This PR updates `golangci-linter-action` version to `v2`
Fixes #
```
none
```

CI: Update golangci/golangci-linter-action to v2

---

Makefile

/kind cleanup
chore: optimize Makefile
Fixes #
```
none
```

chore: optimize Makefile

---

charts/latest/csi-driver-smb/values.yaml
deploy/csi-smb-node-windows.yaml

/kind feature
chore: upgrade node-driver-registrar version to v2.0.1 on windows
Fixes #
```
chore: upgrade node-driver-registrar version to v2.0.1 on windows
```

chore: upgrade node-driver-registrar version to v2.0.1 on windows

---

pkg/smbplugin/Windows.Dockerfile

/kind feature
fix: copy netapi32.dll from windows-servercore-cache instead of servercore
Fixes #
```
fix: copy netapi32.dll from windows-servercore-cache instead of servercore
```

fix: copy netapi32.dll from windows-servercore-cache instead of servercore

---

Makefile
pkg/smbplugin/Dockerfile

/kind feature
chore: optimize build
Fixes #
```
none
```

chore: optimize build

---

deploy/example/storageclass-smb.yaml
pkg/smb/nodeserver.go

/kind bug
fix: domain issue on Windows
Fixes #137
```
/kind bug
```

fix: domain issue on Windows

---

Makefile

/kind bug
fix: windows image build error
This is a workaround fix, wait for buildkit fix on v0.8.0: https://github.com/moby/buildkit/pull/1879
Fixes #
```
fix: windows image build error
```

fix: windows image build error

---

charts/latest/csi-driver-smb/templates/csi-smb-node-windows.yaml
charts/latest/csi-driver-smb/templates/csi-smb-node.yaml

/kind bug
chore: change node registrar path to support linuxPath
Fixes #171
```
chore: change node registrar path to support linuxPath
```

chore: change node registrar path to support linuxPath

---

go.mod
test/sanity/run-test.sh
vendor/modules.txt

/kind cleanup
test: refine sanity test script
Fixes #
```
none
```

test: refine sanity test script

---

test/sanity/run-test.sh

/kind cleanup
test: upgrade sanity-test to v4.0.2
Fixes #
```
none
```

 test: upgrade sanity-test to v4.0.2

---

pkg/smb/nodeserver.go

/kind cleanup
chore: improve logging
Fixes #
```
none
```

chore: improve logging

---

charts/latest/csi-driver-smb/templates/csi-smb-node-windows.yaml
charts/latest/csi-driver-smb/templates/csi-smb-node.yaml

/kind bug
fix: kubeletPath issue in helm installation
fixed issue that when `-set kubelet.linuxPath=/var/snap/microk8s/common/var/lib/kubelet`, helm installation does not work.
Fixes #184
```
fix: kubeletPath issue in helm installation
```

fix: kubeletPath issue in helm installation

---

Makefile

/kind bug
fix: buildkit error in building arm64 image
Fixes #179
```
fix: buildkit error in building arm64 image
```

fix: buildkit error in building arm64 image

---

.github/workflows/darwin.yaml
.github/workflows/ubuntu.yml
.github/workflows/windows.yml

/kind cleanup
test: enable GH actions on all branches
Fixes #
```
none
```

test: enable GH actions on all branches

---

.github/workflows/darwin.yaml
.github/workflows/linux.yaml
.github/workflows/ubuntu-e2e.yml
.github/workflows/windows.yaml
charts/README.md

/kind cleanup
test: switch to use go 1.15
Fixes #
```
none
```

test: switch to use go 1.15

---

go.mod
vendor/modules.txt

/kind cleanup
chore: remove klogv1 in go mod
Fixes #203
```
none
```

chore: remove klogv1 in go mod

---

Makefile
deploy/example/deployment.yaml
deploy/example/statefulset-nonroot.yaml
hack/verify-examples.sh
test/e2e/suite_test.go

/kind cleanup
test: automate example verification test
Fixes #
```
none
```

test: automate example verification test

---

test/e2e/dynamic_provisioning_test.go
test/e2e/suite_test.go
test/e2e/testsuites/dynamically_provisioned_restart_driver_tester.go
test/utils/restart_driver_daemonset.sh

/kind feature
This PR adds an e2e test to ensure that existing pods still have access to volume after restarting the driver daemonset.
Fixes #200
```
none
```
```
none
```

test: Add restart driver e2e test

---

pkg/smb/identityserver.go

/kind cleanup
cleanup: remove useless logs
Fixes #
```
none
```

cleanup: remove useless logs

---

deploy/example/windows/README.md

old link was no longer valid so updated the link.
docs: Documentation 📘
```
none
```

Update windows CSI support link

---

charts/index.yaml
hack/verify-all.sh
hack/verify-helm-chart-files.sh
hack/verify-helm-chart.sh

/kind cleanup
test: add verify-helm-chart-files.sh
Fixes #
```console
helm repo index charts --url=https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
```
```
none
```

test: add verify-helm-chart-files.sh

---

hack/verify-helm-chart-files.sh

/kind cleanup
test: add helm chart index verification
Fixes #
```
none
```

test: add helm chart index verification

---

deploy/example/windows/README.md
deploy/example/windows/deployment.yaml
deploy/example/windows/statefulset.yaml
known-issues.md

doc: add mount error on windows doc
Fixes #
```
none
```

doc: add mount error on windows doc

---

Makefile

/kind cleanup
fix: remove arm64 build workaround
Fixes #
```
none
```

fix: remove arm64 build workaround

---

Makefile
test/external-e2e/run.sh
test/external-e2e/testdriver.yaml

add external e2e tests
Fixes #
```
none
```

Add K8s external storage E2E tests

---

pkg/smbplugin/Dockerfile
test/e2e/testsuites/testsuites.go

/kind bug
chore: upgrade base image to fix CVE issue
test: support GKE windows node toleration
Fixes #
```
chore: upgrade base image to fix CVE issue
```

chore: upgrade base image to fix CVE issue

---

Makefile

/kind cleanup
Cleanup testing secret to add idempotency to "make install-smb-provisioner"
```release-note
NONE
```

cleanup secret before create a new one

---

pkg/smb/nodeserver.go
pkg/smb/nodeserver_test.go

/kind bug
fix: remove unnecessary lock in NodePublish
Fixes #
```
fix: remove unnecessary lock in NodePublish
```

fix: remove unnecessary lock in NodePublish

---

test/external-e2e/run.sh
test/external-e2e/testdriver.yaml

/kind test
test: run 1.21 external test suites
Fixes #
```
none
```

test: run 1.21 external test suites

---

test/run-e2e-test.sh

Add a script to set up and run e2e test. Plan to use it later in prow job.
```
none
```

Add a script to run e2e test

---

deploy/example/e2e_usage.md
pkg/mounter/safe_mounter_windows.go
test/e2e/dynamic_provisioning_test.go
test/e2e/suite_test.go

/kind bug
fix: convert source path on Windows
Fixes #
```
fix: convert source path on Windows
```

fix: convert source path on Windows

---

deploy/example/e2e_usage.md

Fix a typo in the doc
```
none
```

Fix a typo

---

deploy/example/storageclass-smb.yaml
pkg/smb/controllerserver.go
test/external-e2e/run.sh
test/integration/run-test.sh

/kind cleanup
chore: a little cleanup
Fixes #
```
none
```

chore: a little cleanup

---

test/integration/run-test.sh

fix integration tests failure

---

docs/csi-dev.md

Update the doc title and inconsistent path. 
```
none
```

doc: update the title and path in the doc

---

test/run-e2e-test.sh

Add the file path to the make commands. 
```
none
```

test: add file path to make commands

---

test/run-e2e-test.sh

Accidentally commented a line in previous PR. This PR is just to revert the comment. 
```
none
```

revert a comment

---

test/run-e2e-test.sh

Pushing image failed with auth error. Add configure docker to fix the auth.
```
none
```

test: Configure docker in e2e test script

---

pkg/smb/smb.go
pkg/smb/version.go
pkg/smb/version_test.go
pkg/smbplugin/main.go

/kind bug
fix: incorrect display driverName when using alternative driver name
Fixes #
```
fix: incorrect display driverName when using alternative driver name
```

fix: incorrect display driverName when using alternative driver name

---

pkg/smb/version.go
pkg/smb/version_test.go

/kind cleanup
chore: show current driver name
Fixes #
```
none
```

chore: show current driver name

---

pkg/smb/nodeserver.go

/kind bug
fix: unmount failure due to incorrect mount path check
Fixes #
```
fix: unmount failure due to incorrect mount path check
```

fix: unmount failure due to incorrect mount path check

---

.github/workflows/windows.yaml
test/e2e/manifest/windows.json

/kind cleanup
test: switch to csi-proxy-v1.0.0 config
Fixes #
```
none
```

test: switch to csi-proxy-v1.0.0 config

---

test/e2e/manifest/linux-vmss.json
test/e2e/manifest/linux.json

test: remove deprecated test configs
Fixes #
```
none
```

test: remove deprecated test configs

---

pkg/mounter/safe_mounter_v1beta_windows.go
pkg/mounter/safe_mounter_windows.go
pkg/smb/smb_common_windows.go

/kind cleanup
chore: refine CSIProxyMounter interface
Fixes #
```
none
```

chore: refine CSIProxyMounter interface

---

Makefile
docs/csi-dev.md

/kind feature
feat: add windows 20H2 2022 image support
Fixes #
```
feat: add windows 20H2 2022 image support
```

feat: add windows 20H2 2022 image support

---

deploy/example/pv-smb.yaml

doc: change default smb server address in pv config
Fixes #
```
none
```

doc: change default smb server address in pv config

---

Makefile

/kind cleanup
cleanup: remove arm64 build workaround
Fixes #
```
none
```

cleanup: remove arm64 build workaround

---

Makefile

/kind cleanup
cleanup: remove 1903 1909 2004 Windows image which is end of life
Fixes #
```
cleanup: remove 1903 1909 2004 Windows image which is end of life
```

cleanup: remove 1903 1909 2004 Windows image which is end of life

---

.github/workflows/pluto.yaml
Makefile
test/e2e/testsuites/dynamically_provisioned_delete_pod_tester.go

/kind feature
test: add apiVersion deprecation test
Fixes #
```
none
```

test: add apiVersion deprecation test

---

.github/workflows/pluto.yaml
pkg/smbplugin/Dockerfile

/kind bug
fix: CVE-2021-43618 in Ubuntu image
Fixes #
```
test/smb-csi:latest (debian 11.0)
=======================================
Total: 1 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 1, CRITICAL: 0)
+----------+------------------+----------+-------------------+------------------------+---------------------------------------+
| LIBRARY  | VULNERABILITY ID | SEVERITY | INSTALLED VERSION |     FIXED VERSION      |                 TITLE                 |
+----------+------------------+----------+-------------------+------------------------+---------------------------------------+
| libgmp10 | CVE-2021-43618   | HIGH     | 2:6.2.1+dfsg-1    | …
```

fix: CVE-2021-43618 in Ubuntu image

---

deploy/example/e2e_usage.md
deploy/example/storageclass-smb.yaml
test/e2e/dynamic_provisioning_test.go
test/e2e/suite_test.go

/kind cleanup
test: add no subdir creation e2e test
Fixes #
```
none
```

test: add no subdir creation e2e test

---

Makefile
docs/driver-parameters.md
pkg/smb/controllerserver.go
pkg/smb/smb.go
pkg/smb/smb_test.go

/kind feature
feat: support mountOptions in DeleteVolume
> since `DeleteVolumeRequest` does not provide `mountOptions`, following is the workaround to provide `mountOptions` for `DeleteVolume`
- create a secret `smbcreds` with `mountOptions`
```console
kubectl create secret generic smbcreds --from-literal username=USERNAME --from-literal password="PASSWORD" --from-literal mountOptions="dir_mode=0777,file_mode=0777,uid=0,gid=0,mfsymlinks"
```
- set `csi.storage.k8s.io/provisioner-secret-name: "smbcreds"` in storage class
- 
Fixes #
```
feat: support mountOptions in DeleteVolume
```

feat: support mountOptions in DeleteVolume

---

cloudbuild.yaml

/kind cleanup
Missing cloudbuild.yaml file so the job is failing athttps://k8s-testgrid.appspot.com/sig-storage-image-build#post-csi-driver-smb-push-images
```
none
```

publish image to cloud provider repo

---

pkg/smbplugin/Dockerfile

/kind bug
fix: CVE-2021-3996 in image build
Fixes #
```
fix: CVE-2021-3996 in image build
```

fix: CVE-2021-3996 in image build

---

Makefile

/kind feature
feat: add ppc64le arch support
Fixes #
```
feat: add ppc64le arch support
```

feat: add ppc64le arch support

---

hack/verify-all.sh
pkg/smb/nodeserver.go
pkg/smb/nodeserver_test.go

/kind bug
fix: gid conflict issue between sc and fsGroup setting
Fixes #
```
fix: gid conflict issue between sc and fsGroup setting
```

fix: gid conflict issue between sc and fsGroup setting

---

.github/workflows/codeql-analysis.yml
pkg/smbplugin/Dockerfile

/kind bug
fix: CVE-2018-25032 in image build
Fixes #
```
fix: CVE-2018-25032 in image build
```

fix: CVE-2018-25032 in image build

---

deploy/example/e2e_usage.md
deploy/example/pv-smb.yaml
deploy/example/pvc-smb-static.yaml

doc: refine static PV doc
Fixes #
```
none
```

doc: refine static PV doc

---

pkg/mounter/safe_mounter_v1beta_windows.go
pkg/mounter/safe_mounter_windows.go

/kind cleanup
chore: refine logging in Windows mount
Fixes #
```
none
```

chore: refine logging in Windows mount

---

pkg/smb/controllerserver.go
pkg/smb/controllerserver_test.go
test/external-e2e/run.sh
test/integration/run-test.sh

/kind bug
fix: disallow block volume capability
should return error for block volume capability
Fixes #
```
fix: disallow block volume capability
```

fix: disallow block volume capability

---

test/external-e2e/run.sh

test: enable one external test
Fixes #
```
none
```

test: enable one external test

---

pkg/smbplugin/Dockerfile

/kind bug
fix: CVE-2022-1271 in image build
```
+----------+------------------+----------+-------------------+-------------------+--------------------------------------+
| LIBRARY  | VULNERABILITY ID | SEVERITY | INSTALLED VERSION |   FIXED VERSION   |                TITLE                 |
+----------+------------------+----------+-------------------+-------------------+--------------------------------------+
| gzip     | CVE-2022-1271    | HIGH     | 1.10-4            | 1.10-4+deb11u1    | gzip: arbitrary-file-write           |
|          |                  |          |                   |                   | vulnerability                        |
|          |                  |          |                   | …
```

fix: CVE-2022-1271 in image build

---

pkg/smbplugin/Dockerfile

/kind feature
chore: upgrade base image
Fixes #
```
none
```

chore: upgrade base image

---

Makefile

chore: fix canary-csi-driver-smb-push-images build failure
Fixes #
```
none
```

chore: fix canary-csi-driver-smb-push-images build failure

---

cmd/smbplugin/Dockerfile.Windows

chore: fix windows pipeline
Fixes #
```
none
```

chore: fix windows pipeline

---

pkg/csi-common/server_test.go
pkg/mounter/safe_mounter_v1beta_windows.go
pkg/mounter/safe_mounter_windows.go
pkg/smb/controllerserver.go
pkg/smb/fake_mounter.go

test: fix TestLogGRPC ut failure
Fixes #
```
none
```

test: fix TestLogGRPC ut failure

---

charts/index.yaml

/kind bug
Fixes #525
```
none
```

fix: helm chart index error

---

.github/workflows/static.yaml
.github/workflows/trivy.yaml

test: update ubuntu-18.04 to ubuntu-latest in GitHub workflows
Fixes #
```
none
```

test: update ubuntu-18.04 to ubuntu-latest in GitHub workflows

---

.github/workflows/static.yaml

test: fix golint error
Fixes #
```
none
```

test: fix golint error

---

hack/verify-all.sh
hack/verify-helm-chart-index.sh

/kind feature
test: add helm repo install check
Fixes #
```
none
```

test: add helm repo install check

---

deploy/example/pv-smb.yaml

doc: add annotations in PV config to support Delete reclaimPolicy
Fixes #
- this PR fixed following error:
<details>
```
Name:            pv-smb
Labels:          <none>
Annotations:     pv.kubernetes.io/bound-by-controller: yes
Finalizers:      [kubernetes.io/pv-protection]
StorageClass:    smb
Status:          Failed
Claim:           default/pvc-smb
Reclaim Policy:  Delete
Access Modes:    RWX
VolumeMode:      Filesystem
Capacity:        100Gi
Node Affinity:   <none>
Message:         error getting deleter volume plugin for volume "pv-smb": no deletable volume plugin matched
Source:
Type:              CSI (a …
```

doc: add annotations in PV config to support Delete reclaimPolicy

---

pkg/mounter/safe_mounter_unix.go
pkg/smb/smb_common_linux.go

/kind bug
fix: remove forceUmount and lazyUmount
This PR is reverting https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/569since “umount -f -l” (linux force umount & lazy umount) would make the smb mount dir broken(pointing to an invalid device) when there is heavy read write on the smb mount dir to be unmounted.
Fixes #
```
fix: remove forceUmount and lazyUmount
```

fix: remove forceUmount and lazyUmount

---

pkg/smb/controllerserver.go

/kind bug
It creates also parent directories of sub-directories under the mounted base-dir. Just like mkdir -p does.
similar fix as https://github.com/kubernetes-csi/csi-driver-nfs/pull/412
Fixes #
```
fix: use mkdir -p for creating subdir in mounted base-dir
```

fix: use mkdir -p for creating subdir in mounted base-dir

---

release-tools/KUBERNETES_CSI_OWNERS_ALIASES
release-tools/SIDECAR_RELEASE_PROCESS.md
release-tools/filter-junit.go
release-tools/go-get-kubernetes.sh
release-tools/prow.sh
release-tools/verify-spelling.sh

test: update release tools
This is for fixing https://testgrid.k8s.io/sig-storage-image-build#post-csi-driver-smb-push-images
```
git subtree pull --squash --prefix=release-tools https://github.com/kubernetes-csi/csi-release-tools.git master
```
Fixes #
```
none
```

test: update release tools

---

cmd/smbplugin/Dockerfile

/kind cleanup
Update the debian base image to the latest release.
None
None
```release-note
None
```

Update debian-base image to v1.4.3

---

Makefile

/kind cleanup
cleanup: remove 20H2 windows image build
Windows SAC releases (2004, 20H2) have been out-of-support for a while now so we shouldn't build contianer images for those platforms
Fixes #
```
none
```

cleanup: remove 20H2 windows image build

---

deploy/example/statefulset-nonroot.yaml
deploy/example/statefulset.yaml
deploy/example/windows/statefulset.yaml

/kind cleanup
The volume.beta.kubernetes.io/storage-class annotation is deprecated since v1.9.
Changed it to a new way to deal with some e2e issues.
Fixes #
```
none
```

test(e2e): change the storageclass configuration method in the test file

---

pkg/smb/nodeserver.go
pkg/smb/smb_test.go
test/utils/credentials/credentials.go
test/utils/credentials/credentials_test.go

/kind cleanup
Replace the deprecated ioutil method, Because they are no longer recommended in go version 1.16 or 1.17
Fixes #
```
none
```

cleanup: replace deprecated ioutil method

---

deploy/example/pvc-volume-clone.yaml
pkg/csi-common/driver_test.go
pkg/csi-common/utils_test.go
pkg/smb/controllerserver.go
pkg/smb/controllerserver_test.go
pkg/smb/smb.go
test/e2e/dynamic_provisioning_test.go
test/e2e/testsuites/dynamically_provisioned_volume_cloning_tester.go
test/e2e/testsuites/specs.go
test/external-e2e/testdriver.yaml
test/sanity/secrets.yaml

/kind feature
feat: volume clone from source volume 
Fixes #
```
none
```

feat: volume clone from source volume 

---

.github/dependabot.yaml

/kind cleanup
chore: add Dockerfile dependabot
Fixes #
```
none
```

chore: add Dockerfile dependabot

---

release-tools/SIDECAR_RELEASE_PROCESS.md
release-tools/build.make
release-tools/cloudbuild.yaml
release-tools/contrib/get_supported_version_csi-sidecar.py
release-tools/prow.sh

/kind cleanup
chore: update csi-release-tools
Fixes #
```
none
```

chore: update csi-release-tools

---

pkg/smb/controllerserver.go

/kind cleanup
chore: refine delete subDir check
Fixes #
```
none
```

chore: refine delete subDir check

---

cmd/smbplugin/Dockerfile
go.mod
hack/verify-gomod.sh
vendor/modules.txt

/kind feature
feat: switch to bookworm debian base image
bookworm debian base image has fewer CVEs compared to bulleye debian base image
```
==============================================
Total: 97 (UNKNOWN: 0, LOW: 72, MEDIUM: 14, HIGH: 10, CRITICAL: 1)
==============================================
Total: 210 (UNKNOWN: 0, LOW: 104, MEDIUM: 47, HIGH: 50, CRITICAL: 9)
```
Fixes #642
```release-note
feat: switch to bookworm debian base image
```

feat: switch to bookworm debian base image

---

.github/ISSUE_TEMPLATE/bug-report.md

/kind cleanup
This PR corrects the command to list the CSI Driver Version noted in the bug report template. It now instructs to grep for k8s.registry instead of gcr after the registry was replaced - https://github.com/kubernetes-csi/csi-driver-smb/pull/460
Fixes #
I noticed the instruction was incorrect while raising an issue so thought I'd correct it. Please let me know if I need to change anything about this PR, I was unsure how to categorise it.
```
none
```

chore: update bug-report.md gcr to registry.k8s

---

deploy/example/e2e_usage.md
deploy/example/nginx-pod-smb.yaml
deploy/example/pv-smb.yaml
deploy/example/smb-provisioner/pv-smb-csi.yaml
deploy/example/statefulset-nonroot.yaml
deploy/example/statefulset.yaml

doc: fix readOnly setting doc
- following csi.readOnly is not supported in CSI driver
```
csi:
driver: driver-name
readOnly: false
```
Fixes #
```
none
```

doc: fix readOnly setting doc

---

test/utils/smb_log.sh

test: fix capz test failure
Fixes #
```
none
```

test: fix capz test failure

---

.github/workflows/linux.yaml

test: fix github action test failure
Fixes #
```
none
```

test: fix github action test failure

---

deploy/v1.14.0/csi-smb-node-windows.yaml
deploy/v1.14.0/csi-smb-node.yaml

/kind bug
`csi-node-driver-registrar` image version is incorrectly specified in `deploy/v1.14.0` manifests.
(2.12.0 has not been released yet.)
Fixes #
```
none
```

fix: change node-driver-registrar image version to 2.10.0 (deploy/v1.14.0 manifests)

---

docs/driver-parameters.md

doc: fix kerberos auth doc
Fixes #757
```
none
```

doc: fix kerberos auth doc

---

cmd/smbplugin/Dockerfile.Windows

/kind bug
fix: windows image 1809 build failure by using workaround: https://github.com/microsoft/Windows-Containers/issues/493
Fixes #
```
fix: windows image 1809 build failure
```

fix: windows image 1809 build failure

---

charts/index.yaml

Remove 0.15.0 from index.yaml too.
bug/cleanup
As 1.15.0 was removed from the repo, is should also get removed from index.yaml.
Fixes #
```
none
```

Update index.yaml - remove 1.15.0 from index.yaml

---

.github/workflows/trivy.yaml
release-tools/.github/dependabot.yaml
release-tools/.github/workflows/codespell.yml
release-tools/.github/workflows/trivy.yaml
release-tools/SIDECAR_RELEASE_PROCESS.md
release-tools/build.make
release-tools/generate-patch-release-notes.sh
release-tools/go-modules-targeted-update.sh
release-tools/prow.sh
release-tools/verify-logcheck.sh

chore: update release-tools to fix spelling error
Fixes #
```release-note
none
```

chore: update release-tools to fix spelling error

---

Makefile
deploy/example/cloning/nginx-pod-restored-cloning.yaml
deploy/example/daemonset-ephemeral.yaml
deploy/example/deployment.yaml
deploy/example/nginx-pod-smb.yaml
deploy/example/pvc-smb-static.yaml
deploy/example/pvc-smb.yaml
deploy/example/smb-provisioner/smb-server-lb.yaml
deploy/example/smb-provisioner/smb-server-networkdisk.yaml
deploy/example/smb-provisioner/smb-server.yaml
deploy/example/statefulset-nonroot.yaml
deploy/example/statefulset.yaml
deploy/example/windows/deployment.yaml
deploy/example/windows/statefulset.yaml
hack/verify-examples.sh
test/e2e/suite_test.go

test: add default namespace in examples to fix e2e test failure
Fixes #
```release-note
none
```

test: add default namespace in examples to fix e2e test failure

---

Makefile

test: fix external test failure
Fixes #
```
none
```

test: fix external test failure

---

Makefile

/kind cleanup
cleanup: use one image tag in e2e test
Fixes #
```
none
```

cleanup: use one image tag in e2e test

---

test/e2e/dynamic_provisioning_test.go

test: skip one flacky windows test
Fixes #
```
none
```

test: skip one flacky windows test

---

support.md

doc: add support doc
Fixes #
```
none
```

doc: add support doc

---

.github/workflows/static.yaml
pkg/csi-common/utils_test.go
pkg/smb/controllerserver.go
pkg/smb/controllerserver_test.go
pkg/smb/nodeserver.go
pkg/smb/nodeserver_test.go
pkg/smb/smb.go
pkg/smb/smb_test.go
test/e2e/dynamic_provisioning_test.go

/kind cleanup
chore: upgrade golint version
Fixes #
```
none
```

chore: upgrade golint version

---

pkg/smb/smb_test.go

test: fix random ut failure
Fixes #
```
none
```

test: fix random ut failure

---

test/e2e/suite_test.go

- Sometime we installed the smb provisioner with a fix/manual build version(do not use the default helm version) and want to execute the e2e tests, introduce the `export PRE_INSTALL_SMB_PROVISIONER=true` could help us omit the install/uninstall step in `BeforeSuite` and `AfterSuite`.
Fixes #
```
none
```

test: use env var for enable driver install in e2e

---

release-tools/build.make
release-tools/prow.sh

/kind bug
fix: build with go 1.22.5 to fix golang CVE
Fixes #855
```
fix: build with go 1.22.5 to fix golang CVE
```

fix: build with go 1.22.5 to fix golang CVE

---

release-tools/build.make
release-tools/prow.sh
release-tools/pull-test.sh

/kind cleanup
chore: upgrade release tools
```
git subtree pull --squash --prefix=release-tools https://github.com/kubernetes-csi/csi-release-tools.git master
```
Fixes #
```
none
```

chore: upgrade release tools

---

go.mod

/kind bug
fix: use godebug winsymlink
refer to https://github.com/kubernetes/kubernetes/issues/129080
Fixes #
```
fix: use godebug winsymlink on Windows build
```

fix: use godebug winsymlink on Windows build

---

test/sanity/run-test.sh

/kind cleanup
test: upgrade csi-test to v5.3.1
Fixes #
```
none
```

test: upgrade csi-test to v5.3.1

---

go.mod
go.sum
vendor/golang.org/x/net/html/doc.go
vendor/golang.org/x/net/html/doctype.go
vendor/golang.org/x/net/html/foreign.go
vendor/golang.org/x/net/html/iter.go
vendor/golang.org/x/net/html/node.go
vendor/golang.org/x/net/html/parse.go
vendor/golang.org/x/net/http2/client_conn_pool.go
vendor/golang.org/x/net/http2/config.go
vendor/golang.org/x/net/http2/config_go124.go
vendor/golang.org/x/net/http2/config_pre_go124.go
vendor/golang.org/x/net/http2/frame.go
vendor/golang.org/x/net/http2/http2.go
vendor/golang.org/x/net/http2/server.go
vendor/golang.org/x/net/http2/transport.go
vendor/golang.org/x/net/http2/unencrypted.go
vendor/golang.org/x/net/http2/write.go
vendor/golang.org/x/net/websocket/websocket.go
vendor/modules.txt

/kind bug
fix: CVE-2024-45338
```
azurediskplugin (gobinary)
==========================
Total: 1 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 1, CRITICAL: 0)
┌──────────────────┬────────────────┬──────────┬────────┬───────────────────┬───────────────┬───────────────────────────────────────────────────┐
│     Library      │ Vulnerability  │ Severity │ Status │ Installed Version │ Fixed Version │                       Title                       │
├──────────────────┼────────────────┼──────────┼────────┼───────────────────┼───────────────┼───────────────────────────────────────────────────┤
│ golang.org/x/net │ CVE-2024-45338 │ HIGH     │ fixed  │ v0.32.0           │ 0.33.0        │ Non-linear parsing of case-insensitive content …
```

fix: CVE-2024-45338

---

release-tools/cloudbuild.yaml
release-tools/prow.sh

/kind cleanup
chore: Update csi release tools
```
git subtree pull --squash --prefix=release-tools https://github.com/kubernetes-csi/csi-release-tools.git master
```
Fixes #
```
none
```

chore: Update csi release tools

---

cmd/smbplugin/main.go
cmd/smbplugin/main_test.go

/kind test
test: add unit test for main function
Fixes #
```
none
```

test: add unit test for main function

---

release-tools/build.make

/kind feature
chore: support windows hpc image build
Fixes #
```
none
```

chore: support windows hpc image build

---

test/e2e/suite_test.go
test/utils/create_smbcreds_windows.sh

test: fix windows hpc test failure
Fixes #
```
none
```

test: fix windows hpc test failure

---

test/e2e/dynamic_provisioning_test.go

- As we introduce use env var for smb server configuration in https://github.com/kubernetes-csi/csi-driver-smb/pull/773, we'd better also use the env var for CSI inline volume test secret, otherwise when users already use the env var for custom setting the case will be failed.
Fixes #
```
none
```

test: use env var for CSI inline volume test secret

---

test/external-e2e/testdriver.yaml

- In https://github.com/kubernetes-csi/csi-driver-smb/pull/881 the volume resize support added while the driver itself does not impel(support) NodeExpandVolume  in https://github.com/kubernetes-csi/csi-driver-smb/blob/master/pkg/smb/nodeserver.go , though it does not impact the tests we'd better correct the test capabilities to keep consistent with what actually supports.
Fixes #
```
none
```

test: correct external-e2e driver capabilities

---

go.mod
go.sum
vendor/github.com/golang-jwt/jwt/v4/parser.go
vendor/modules.txt

/kind bug
fix: CVE-2025-30204
Fixes #
```
fix: CVE-2025-30204
```

fix: CVE-2025-30204

---

.github/workflows/static.yaml
go.mod
pkg/csi-common/utils.go
pkg/smb/controllerserver_test.go
release-tools/prow.sh

/kind cleanup
chore: use go1.24
Fixes #
```release-note
NONE
```

chore: use go1.24
