kubernetes-csi/csi-driver-smb

- .travis.yml
- pkg/smb/controllerserver.go
- pkg/smb/nodeserver.go
- test/sanity/README.md
- test/sanity/run-test.sh
/kind test
test: enable sanity test
Fixes #6
There is one sanity test should enable it later, need to figure out how to set volumeContext in `NodeStageVolume` in sanity test.
```
• Failure [0.003 seconds]
Node Service
/root/go/pkg/mod/github.com/kubernetes-csi/csi-test@v2.2.0+incompatible/pkg/sanity/tests.go:44
should work [It]
/root/go/pkg/mod/github.com/kubernetes-csi/csi-test@v2.2.0+incompatible/pkg/sanity/node.go:643
Unexpected error:
<*status.statusError | 0xc0001ecff0>: {
Code: 3,
Message: "source field is missing, current context: map[]",
Details: nil,
XXX_NoUnkeyedLiteral: {},
XXX_unrecognized: nil,
XXX_sizecache: 0,
}
rpc …
```
> test: enable sanity test

- pkg/smb/nodeserver_test.go
- pkg/smb/smb_test.go
/kind test
/kind flake
This PR skips the following tests in `pkg/smb` when running on Windows environment:
- `TestNodeStageVolume`
- `TestNodePublishVolume`
- `TestNodeUnpublishVolume`
- `TestNodeUnstageVolume`
- `TestIsCorruptedDir`
Fixes #82
```
none
```
> Skip unit tests in windows

- .github/workflows/go.yml
- .github/workflows/windows.yml
Currently 
/kind cleanup
Currently half of the tests are in GitHub workflows and few others in travis.yml. With this change, except e2e tests, everything else be moved to GitHub workflows. 
Fixes #54
```
none
```
> move integration tests into github workflows

- charts/README.md
- charts/latest/csi-driver-smb/templates/csi-smb-node-windows.yaml
- charts/latest/csi-driver-smb/templates/csi-smb-node.yaml
- charts/latest/csi-driver-smb/values.yaml
/kind cleanup
Typically when setting kubernetes, the Kubelet path varies for different kind of setups. For example in Racher2 boxes, the Kubelet path is `/opt/rke/var/lib/kubelet/` not `/var/lib/kubelet/`
The changes in this PR help make the Kubelet path configurable from helm template 
Fixes #69 
```
Ability to make Kubelet path configurable from helm template
```
> make kubelet path configurable from helm values

- pkg/csi-common/controllerserver-default.go
- pkg/csi-common/identityserver-default.go
- pkg/csi-common/nodeserver-default.go
- pkg/csi-common/utils.go
As of go1.7, package context is [available](https://godoc.org/golang.org/x/net/context) in standard library. So using the default package everywhere.
/kind cleanup
Keeps the code up-to-date by using newer code.
Fixes #
```
none
```
> replace all `golang.org/x/net/context` with context

- pkg/smb/fake_mounter_test.go
- pkg/smb/nodeserver.go
- pkg/smb/nodeserver_test.go
- test/utils/testutil/testutil.go
Fix `TestNodeStageVolume` on Windows
Fixes #
```
none
```
> test: Fix `TestNodeStageVolume` on Windows

- .github/workflows/static.yaml
CI: Use `golangci-lint-action` for running linters
Fixes https://github.com/kubernetes-csi/csi-driver-smb/issues/118
```
none
```
> CI: Use `golangci-lint-action` for running linters

- .github/workflows/windows.yml
/kind test
Currently we are skipping a lot of test cases in windows. This is because using a fakeMounter to test on windows is causing isues. This PR lays a basic foundations to run windows based tests related to node by running [CSI-Proxy](https://github.com/kubernetes-csi/csi-proxy) as a background job and the all the mount related operation will be handled by this proxy. For more in-depth design details for CSI-Proxy, please refer to the design doc: https://github.com/kubernetes/enhancements/blob/master/keps/sig-windows/20190714-windows-csi-support.md
Added a script to `.github.com/workflows/windows.yml` that downloads and starts …
> Lay foundations for re-enabling windows tests: Start CSI-Proxy as a background Job.

- .github/workflows/static.yaml
chore: remove redundant `hack/*` scripts and move linting to static checks
/kind cleanup
- Remove redundant scripts from `hack/*` and introduce them as a part of golangci-linter
Fixes #
```
none
```
> CI: add `golint` and `misspell` to static checks

- .github/workflows/darwin.yaml
- .github/workflows/ubuntu.yml
- .github/workflows/windows.yml
- charts/latest/csi-driver-smb/templates/csi-smb-controller.yaml
- charts/latest/csi-driver-smb/templates/csi-smb-node.yaml
- deploy/csi-smb-controller.yaml
- deploy/csi-smb-node.yaml
- pkg/smbplugin/Dockerfile
- pkg/smbplugin/dev.Dockerfile
Reverts kubernetes-csi/csi-driver-smb#124
Original PR did not improve the security, that PR is just for bypass security scanning, while would introduce various permission setting issue.
> Revert "fix: create nonroot user in Dockerfile"

- .github/workflows/ubuntu-e2e.yml
- Makefile
- test/utils/deploy-kind.sh
This PR adds setting up e2e testing in GitHub action using [kind](https://kind.sigs.k8s.io/docs/user/quick-start/). Kind helps us do e2e tests on various Kubernetes versions and it's also pretty lightweight.
helps in our efforts to move tests to Github actions.
Fixes #
```
none
```
> setup e2e tests in github actions

- Makefile
/kind feature
Add support for ARM64.
Fixes #138
```
none
```
> feat: Add ARM64 support

- charts/latest/csi-driver-smb/templates/csi-smb-node-windows.yaml
- deploy/csi-smb-node-windows.yaml
Remove security context with "privileged: true" setting 
DaemonSet in Windows node is not allowed to perform privileged actions so privileged field in security context shouldn't be true.
/kind bug
Fixes #
fix: Bug Fixes 🐞
```
Remove security context with "privileged: true" setting on Windows node
```
> Remove security context with "privileged: true" setting on Windows node

- pkg/smb/nodeserver.go
- pkg/smb/nodeserver_test.go
- pkg/smb/smb.go
- pkg/smb/volume_lock.go
/kind bug
We don't correctly handle concurrent processing of NodeUnstage call if a previous NodeStage was in-progress and same thing applies to NodeUnpublish call too.
The specs says, if an operation is in-progress for the volume then SP should return error code "10 ABORTED".
Fixes #208 
```
none
```
```
none
```
> fix: Handle concurrent operation of NodeUnstage with NodeStage and NodeUnpublish with NodePublish

- charts/latest/csi-driver-smb/templates/csi-smb-controller.yaml
- charts/latest/csi-driver-smb/templates/csi-smb-node-windows.yaml
- charts/latest/csi-driver-smb/templates/csi-smb-node.yaml
- deploy/csi-smb-controller.yaml
- deploy/csi-smb-node-windows.yaml
- deploy/csi-smb-node.yaml
- hack/verify-examples.sh
- pkg/csi-common/controllerserver-default.go
- pkg/csi-common/identityserver-default.go
- pkg/csi-common/nodeserver-default.go
- pkg/csi-common/utils.go
- pkg/csi-common/utils_test.go
/kind bug
fix: reduce driver logs
- don't print following method logs by default
following 3 method logs constitute 99.8% logs of all driver logs, this PR set the log level of following 3 methods as `10`, and it would not show in driver logs by default(<= `5` will show in driver logs)
```
/csi.v1.Identity/Probe
/csi.v1.Node/NodeGetCapabilities
/csi.v1.Node/NodeGetVolumeStats
```
- set log level of csi side car contains as 2
This could reduce `17,280` logs every day of csi-provisioner, csi-resizer, etc which has lease election, following logs would show every 5s:
```
I0119 12:57:02.073355       1 leaderelection.go:282] successfully renewed lease kube-system/blob-csi-azure-com
I0119 12:57:07.081182       1 …
```
> fix: reduce driver logs

- test/e2e/manifest/windows.json
/kind bug
Optionally add one or more of the following kinds if applicable:
Updates windows image version to use in the e2e test manifest. New windows version has mitigation for driver DaemonSet crashes.
Fixes https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/553
@andyzhangx Please review.
```
none
```
> fix: Use new windows server image to avoid driver daemonset failure

- test/e2e/dynamic_provisioning_test.go
- test/e2e/testsuites/dynamically_provisioned_volume_subpath_tester.go
- test/e2e/testsuites/specs.go
- test/e2e/testsuites/testsuites.go
/kind flake
**What this PR does / why we need it**: 
Add e2e test for volume subpath mount
Fixes #229 
```
none
```
> Add e2e test for volume subpath mount

- Makefile
- docs/csi-dev.md
- pkg/smbplugin/Dockerfile
- pkg/smbplugin/Windows.Dockerfile
- pkg/smbplugin/dev.Dockerfile
- test/integration/run-test.sh
- test/sanity/run-test.sh
/kind bug
fix: arm64 container build
Fixes the Makefile container-all target to build the correct architecture binary and splits outputs into architecture-specific directories to ensure the correct binary is used when building the container image.
Fixes #
```
fix: arm64 container build issue
```
> fix: arm64 container build issue

- deploy/example/smb-provisioner/smb-server-lb.yaml
- deploy/example/smb-provisioner/smb-server.yaml
/kind bug
root path is read-only for nodes in gce clusters and /home/kubernetes is writable so update the path to /home/kubernetes/smbshare-volume
```
none
```
> Update path in hostPath example

- test/utils/credentials/credentials.go
- test/utils/testutil/testutil.go
/kind bug
Current IsRunningInProw check only covers for Azure, add GCP as well. 
```
none
```
> Update IsRunningInProw check

- Makefile
/kind bug
Can't use Helm to install driver for Windows because Windows does not support privileged containers. Change to use kubectl to install drivers. 
```
none
```
> Update helm install

- pkg/smb/nodeserver.go
- pkg/smb/smb_common_linux.go
/kind bug
fix: unmount stuck issue when smb file share is not found
related to https://github.com/kubernetes/kubernetes/issues/97031
Fixes #
```
fix: unmount stuck issue when smb file share is not found
```
> fix: unmount stuck issue when smb file share is not found

- deploy/example/smb-provisioner/README.md
- deploy/example/smb-provisioner/smb-server-networkdisk.yaml
/kind cleanup
The samba server deployment using default storageclass works for both Azure disk and PD. Update the names in the yaml file and docs to point this out. 
```
none
```
> Change samba server yaml using default sc to be more general

- test/run-e2e-test.sh
Remove the unnecessary () in the script/
```
none
```
> Remove unnecessary ()

- Makefile
Add version option to e2e bootstrap. This adds the flexibility to install different release of the driver for e2e test.  
```
none
```
> Add version option for e2e-bootstrap

- Makefile
/kind bug
registry_fix shall be empty for non dockerhub registries. Currently it returns docker.io for some registry like gcr.io/xyz
```
none
```
> fix registry prefix in push-manifest

- test/run-e2e-test.sh
Update the test script to use bosko project gcr registry
```
none
```
> Change to use bosko project gcr registry for e2e test

- deploy/csi-smb-node-windows.yaml
/kind feature
Currently we can't deploy the driver to clusters with nodes based on Windows Server 2022 because `mcr.microsoft.com/oss/kubernetes-csi/livenessprobe:v2.4.0` doesn't support it. But `v2.5.0` does it.
So, if we just update version to v2.5.0 we can add support Windows Servers 2004, 20h2, 2022.
```
none
```
> update livenessprobe to 2.5.0 to add support Windows Server 2022

- .github/workflows/static.yaml
- deploy/example/e2e_usage.md
- deploy/example/storageclass-smb.yaml
- docs/driver-parameters.md
- pkg/smb/controllerserver.go
- pkg/smb/controllerserver_test.go
- pkg/smb/nodeserver.go
- pkg/smb/smb.go
- test/e2e/dynamic_provisioning_test.go
- test/e2e/suite_test.go
/kind feature
feat: add subDir in storage class parameters, e.g.
```yaml
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
name: smb
provisioner: smb.csi.k8s.io
parameters:
source: "//smb-server.default.svc.cluster.local/share"
subDir: "existingSubDirectoryName"  # optional
csi.storage.k8s.io/node-stage-secret-name: "smbcreds"
csi.storage.k8s.io/node-stage-secret-namespace: "default"
volumeBindingMode: Immediate
mountOptions:
- dir_mode=0777
- file_mode=0777
- uid=1001
- gid=1001
```
Fixes #398
```
feat: add subDir in storage class parameters
```
> feat: add subDir in storage class parameters

- Makefile
chore: fix arm v7 build issue
This PR fixed the following build error:
```
#6 48.68 Setting up python3-minimal (3.9.2-3) ...
#6 51.26 Traceback (most recent call last):
#6 51.26   File "/usr/bin/py3compile", line 319, in <module>
#6 51.26     main()
#6 51.26   File "/usr/bin/py3compile", line 280, in main
#6 51.26     pkg_files = tuple(dpf.from_package(options.package))
#6 51.26   File "/usr/share/python3/debpython/files.py", line 53, in from_package
#6 51.26     raise Exception("cannot get content of %s" % package_name)
#6 51.26 Exception: cannot get content of python3-minimal
#6 51.31 dpkg: error processing package python3-minimal (--configure):
#6 51.31  installed python3-minimal package …
```
> chore: fix arm v7 build issue

- Makefile
- cloudbuild.yaml
/kind cleanup
Cloudbuild has been failing ([testgrid](https://k8s-testgrid.appspot.com/sig-storage-image-build#post-csi-driver-smb-push-images)). I think this should fix it.
- [N/A ] includes documentation
- [ N/A] adds unit tests
- [ N/A ] tested upgrade from previous version
```
none
```
> Tweak make rules to make cloudbuild work

- pkg/smbplugin/Dockerfile
- pkg/smbplugin/Windows.Dockerfile
/kind bug
fix: CVE issues in image build
Fixes #
```
+-------------+------------------+----------+-------------------+-----------------+---------------------------------------+
|   LIBRARY   | VULNERABILITY ID | SEVERITY | INSTALLED VERSION |  FIXED VERSION  |                 TITLE                 |
+-------------+------------------+----------+-------------------+-----------------+---------------------------------------+
| libc-bin    | CVE-2021-33574   | CRITICAL | 2.31-13+deb11u2   | 2.31-13+deb11u3 | glibc: mq_notify does                 |
|             |                  |          |                   |                 | not …
```
> fix: CVE issues in image build

- pkg/smb/nodeserver.go
/kind feature
feat: support guest login option `- guest`
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
name: smb
provisioner: smb.csi.k8s.io
parameters:
source: "//smb-server.default.svc.cluster.local/share"
#csi.storage.k8s.io/provisioner-secret-name: "smbcreds"
#csi.storage.k8s.io/provisioner-secret-namespace: "default"
#csi.storage.k8s.io/node-stage-secret-name: "smbcreds"
#csi.storage.k8s.io/node-stage-secret-namespace: "default"
volumeBindingMode: Immediate
mountOptions:
- dir_mode=0777
- file_mode=0777
- uid=1001
- gid=1001
- noperm
- mfsymlinks
- cache=strict
- noserverino  # required to prevent data corruption
- guest
```
Fixes #
**Special …
> feat: support guest login option

- deploy/example/windows/README.md
- deploy/example/windows/csi-proxy.yaml
doc: update csi-proxy install doc
Fixes #
```
none
```
> doc: update csi-proxy install doc

- docs/driver-parameters.md
- pkg/smb/controllerserver.go
- pkg/smb/controllerserver_test.go
- pkg/smb/smb.go
- pkg/smb/smb_test.go
- test/e2e/dynamic_provisioning_test.go
- test/e2e/suite_test.go
/kind feature
feat: create subdir if not exists
In original behavior, `subDir` must exist if it's provided in storage class, this PR would create subdir if not exists
Fixes #
```
feat: create subdir if not exists
```
> feat: create subdir if not exists

- pkg/mounter/refcounter_windows.go
- pkg/mounter/refcounter_windows_test.go
- pkg/mounter/safe_mounter_windows.go
- pkg/smb/nodeserver.go
- pkg/smb/nodeserver_test.go
/kind feature
This PR implement SMBUnmount method to call RemoveSmbGlobalMapping from csi-proxy
Currently no one calls RemoveSmbGlobalMapping 
Make sense to see together with https://github.com/kubernetes-csi/csi-proxy/pull/210
```
Calls RemoveSmbGlobalMapping when it necessary
```
> Calls RemoveSmbGlobalMapping when it necessary

- go.mod
- go.sum
- test/sanity/run-test.sh
- vendor/golang.org/x/net/AUTHORS
- vendor/golang.org/x/net/CONTRIBUTORS
- vendor/golang.org/x/net/context/context.go
- vendor/golang.org/x/net/context/go17.go
- vendor/golang.org/x/net/context/pre_go17.go
- vendor/golang.org/x/net/html/render.go
- vendor/golang.org/x/net/html/token.go
- vendor/golang.org/x/net/http/httpguts/httplex.go
- vendor/golang.org/x/net/http2/client_conn_pool.go
- vendor/golang.org/x/net/http2/errors.go
- vendor/golang.org/x/net/http2/frame.go
- vendor/golang.org/x/net/http2/hpack/encode.go
- vendor/golang.org/x/net/http2/hpack/hpack.go
- vendor/golang.org/x/net/http2/hpack/huffman.go
- vendor/golang.org/x/net/http2/http2.go
- vendor/golang.org/x/net/http2/server.go
- vendor/golang.org/x/net/http2/transport.go
- vendor/golang.org/x/net/http2/writesched_priority.go
- vendor/golang.org/x/net/idna/trieval.go
- vendor/modules.txt
test: run sanity test using csi-test v5.0.0
Fixes #
```
none
```
> test: run sanity test using csi-test v5.0.0

- CONTRIBUTING.md
Signed-off-by: amolmote <amolmote201@gmail.com>
Fixes #538
> updated  CONTRIBUTING.md fix broken link

- README.md
- deploy/example/e2e_usage.md
- deploy/example/smb-provisioner/pv-smb-csi.yaml
doc: refine doc
Fixes #
```
none
```
> doc: refine doc

- deploy/example/storageclass-smb-krb5.yaml
- docs/driver-parameters.md
- pkg/smb/nodeserver.go
- pkg/smb/nodeserver_test.go
- pkg/smb/smb.go
/kind feature
Adding support for more secure mounting, without exposing password
Fixes #512 
```
Adding support for passwordless mounting on linux using provided kerberos credential cache with tickets. 
```
> feat: add support for sec=krb5 mounting

- test/external-e2e/run.sh
- test/utils/deploy-kind.sh
- test/utils/deploy-minikube.sh
…se with https://dl.k8s.io
/kind cleanup
/kind deprecation
Replaces `https://storage.googleapis.com/kubernetes-release` with `https://dl.k8s.io`
Fixes https://github.com/kubernetes/k8s.io/issues/2396
```
none
```
> replace references of https://storage.googleapis.com/kubernetes-release with https://dl.k8s.io

- cmd/smbplugin/Dockerfile
Upon running master branch the following error was showing:
May 11 10:19:42 worker-02 cifs.upcall: get_existing_cc: default ccache is FILE:/tmp/krb5cc_0
Checked on the host and the configuration was appropriate, mounting a cifs share did work approrpiately.
This error was showing specifically inside the smb container, so adding the configuration for the default krb5 cc path as expected by this sci.
/kind bug
Added default krb5.conf to the Dockerfile in `cmd/smbplugin/Dockerfile` with content:
```
[libdefaults]
default_ccache_name = FILE:/var/lib/kubelet/kerberos/krb5cc_%{uid}
```
**Which issue(s) this PR fixes**: #612
Fixes #
```
Added default …
```
> fix: add default krb5 cc path

- docs/driver-parameters.md
- pkg/smb/nodeserver.go
- pkg/smb/nodeserver_test.go
Extending initial support for kerberos-based ticket mounting. Previously, cache has been written directly to the expected file - krb5cc_*. With this change, cache is written to the base64(volumeID) file, and then symlink krb5cc_* created pointing to the file with the cache. During unstage phase only volumeID and mount path is available, and having volumeID it's possible to do the cleanup with simple traversing directory containing the caches.
/kind feature
Adding kerberos cache files cleanup, that will improve use of driver, and remove onus from end users to actually clean those cache files.
```
Kerberos cache files …
```
> Cleaning kerberos cache files on unstage phase

- deploy/example/windows/csi-proxy.yaml
/kind deprecation
/kind feature
Fix to upstream version
All bugs fixed between 1.0.2 and 1.1.2 of csi proxy.
chore: Maintenance 🔧
docs: Documentation 📘
```
Image for csi-proxy updated to 1.1.2
```
> Version 1.1.2 is latest

- README.md
- release-tools/SIDECAR_RELEASE_PROCESS.md
fixing the broken links of testgrid dashboard
The domain name of the testgrid dashboard was updated from k8s-testgrid.appspot.com to testgrid.k8s.io. After the update old domain now throws a 'page not found error'. So fixing the broken links of testgrid dashboard.
This is related to an umbrella issue and fixes a task of the same:
https://github.com/kubernetes/test-infra/issues/30370
> fixed broken links of testgrid dashboard

- pkg/mounter/refcounter_windows.go
- pkg/mounter/refcounter_windows_test.go
- pkg/mounter/safe_mounter_v1beta_windows.go
- pkg/mounter/safe_mounter_windows.go
- pkg/smb/nodeserver.go
- pkg/smb/smb_common_darwin.go
- pkg/smb/smb_common_linux.go
- pkg/smb/smb_common_windows.go
/kind bug
The driver calls Remove-SmbGlobalMapping when it still required for other volumes.
How to reproduce the issue:
1. create persistent volume A without storageClass for \\fileserver\fileshare
2. create persistent volume B without storageClass for the same path (\\fileserver\fileshare)
3. create pv claims AC and BC
4. create pods AP with mounted pvc AC and pod BP with mounted BC
5. remove only pod AP
6. the drivers calls Remove-SmbGlobalMapping for \\fileserver\fileshare <== bug
```
[fix] reference counting of used volumes on Windows nodes
```
> [fix] reference counting of used volumes on Windows nodes

- .github/workflows/static.yaml
- .golangci.yml
- cmd/smbplugin/main.go
- pkg/csi-common/server_test.go
- pkg/mounter/safe_mounter_unix.go
- pkg/smb/controllerserver.go
- pkg/smb/fake_mounter.go
- pkg/smb/identityserver.go
- pkg/smb/nodeserver.go
- pkg/smb/smb.go
- pkg/smb/smb_common_linux.go
- test/e2e/driver/smb_driver.go
- test/e2e/testsuites/specs.go
- test/utils/azure/azure_helpers.go
/kind test
test: upgrade golangci/golangci-lint-action to v1.54
Fixes #
```
none
```
> test: upgrade golangci/golangci-lint-action to v1.54

- release-tools/KUBERNETES_CSI_OWNERS_ALIASES
- release-tools/SIDECAR_RELEASE_PROCESS.md
- release-tools/go-modules-update.sh
- release-tools/prow.sh
chore: Update release tools
```
git checkout -b update_release-tools4
git subtree pull --squash --prefix=release-tools https://github.com/kubernetes-csi/csi-release-tools.git master
git push origin update_release-tools4
```
Fixes #
```
none
```
> chore: Update release tools

- pkg/smb/nodeserver.go
- pkg/smb/nodeserver_test.go
/kind bug
fix: reduce mount lock to avoid volumeID collision issue
the volumeHandle(volumeID) could be duplicated in PV, and duplicated volumeHandle(volumeID) is already allowed in latest k8s version, this PR reduces mount lock to avoid volumeID collision issue, the lock only happen when volumeID + stagingPath is the same
Fixes #
```
fix: reduce mount lock to avoid volumeID collision issue
```
> fix: reduce mount lock to avoid volumeID collision issue

- test/e2e/dynamic_provisioning_test.go
- test/e2e/suite_test.go
- test/utils/check_driver_pods_restart.sh
- Fixed run the e2e test locally the smbDriver nil pointer issue
- Use env var for smb server configuration to make e2e test execute in different test clusters more flexibility.
- Use obvious mountOption in case to make e2e test could be executed in some different smb server configurations
Fixes #
```
none
```
> test: use env var for smb server configuration

- pkg/smb/controllerserver.go
The user might put non-unique spec for subdir:
```
subDir: ${pvc.metadata.namespace}/${pvc.metadata.name}
```
Then, `os.Rename(internalVolumePath, archivedInternalVolumePath)` can fail becaue the destination (`archivedInternalVolumePath`) already exists. It's safer to remove it before `os.Rename()`.
/kind bug
Sensitive user data may leak across Pod create/delete in spite of reclaim policy "Delete". See https://github.com/kubernetes-csi/csi-driver-smb/security/advisories/GHSA-rmg6-rh96-c9wx for details.
Fixes https://github.com/kubernetes-csi/csi-driver-smb/security/advisories/GHSA-rmg6-rh96-c9wx
```
Previously, in archiveOnDelete …
```
> fix: Remove stale archived volume copy before Rename

- test/e2e/testsuites/dynamically_provisioned_reclaim_policy_tester.go
- Enhance e2e test resource clean up
- DynamicallyProvisionedReclaimPolicyTests does not clean up the storageclass after case exit
Fixes #
```
none
```
> test: fix storageclass uncleaned

- Makefile
Modern GNU make (version >= 4.4) has backward-incompatible feature:
> * WARNING: Backward-incompatibility!
>  Previously makefile variables marked as export were not exported to commands
>  started by the $(shell ...) function.  Now, all exported variables are
>  exported to $(shell ...).  If this leads to recursion during expansion, then
>  for backward-compatibility the value from the original environment is used.
This makes any invocation of `make` command very costly. Compare the performance of make 4.3 vs. 4.4:
```
$ time ~/Sources/make-4.3/make smb ARCH=$(go env GOARCH)
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -ldflags "-X github.com/kubernetes-csi/csi-driver-smb/pkg/smb.driverVersion=v1.15.0 -X github.com/kubernetes-csi/csi-driver-smb/pkg/smb.gitCommit=f5ced814f628ddee2c9f3 …
```
> fix: Remove excessive recursive variable expansions

- Makefile
- cmd/smbplugin/Dockerfile.Windows
- test/e2e/suite_test.go
- test/utils/get_smb_svc_public_ip.sh
- test/utils/smb_log.sh
test: fix windows 2019 test failure
Fixes #
```
none
```
> test: fix windows test failure2

- deploy/example/windows/deployment.yaml
- deploy/example/windows/statefulset.yaml
- test/e2e/dynamic_provisioning_test.go
- test/e2e/suite_test.go
- test/e2e/testsuites/specs.go
- test/e2e/testsuites/testsuites.go
test: fix windows 2022 test failure
Fixes #
```
none
```
> test: fix windows 2022 test failure

- pkg/smb/controllerserver.go
- pkg/smb/smb.go
/kind bug
fix: delete volume error in archive deletion mode 
when `onDelete: archive`, there could be delete volume error with error msg `rename xxx: no such file or directory` since there is a bug in csi-provisioner that DeleteVolume may be performed twice, this PR adds a 1 min cache and lock to workaround this issue.
```
[pod/csi-smb-controller-79db546bb6-rn2bd/smb] I0829 08:02:15.334699       1 utils.go:76] GRPC call: /csi.v1.Controller/DeleteVolume
[pod/csi-smb-controller-79db546bb6-rn2bd/smb] I0829 08:02:15.334752       1 utils.go:77] GRPC request: {"secrets":"***stripped***","volume_id":"135.236.234.180/share#smb-4792/pvc-ckk2v#pvc-b1130ed7-05eb-4a93-99ff-92b80fc82ac2#archive"} …
```
> fix: delete volume error in archive deletion mode

- pkg/smb/controllerserver.go
os.RemoveAll() fails if at least one subdir doesn't have write permissions. See https://github.com/kubernetes-csi/csi-driver-smb/issues/834.
/kind bug
Fixes https://github.com/kubernetes-csi/csi-driver-smb/issues/834
```
none
```
> fix: chmod volume dir before deletion

- .github/workflows/trivy.yaml
- pkg/smb/controllerserver.go
- pkg/smb/smb.go
- pkg/smb/smb_test.go
/kind bug
fix: mount with 0777 in volume creation and deletion
fix: https://github.com/kubernetes-csi/csi-driver-smb/pull/840#discussion_r1745816387
Fixes #
```
none
```
> fix: mount with 0777 in volume creation and deletion

- pkg/smb/controllerserver.go
- pkg/smb/smb.go
- pkg/smb/smb_test.go
- test/e2e/suite_test.go
/kind bug
fix: remove parent dir in DeleteVolume
Fixes #
<details>
```
[pod/csi-smb-controller-794dfcb554-sd6gc/smb] I0915 05:07:46.821458       1 utils.go:76] GRPC call: /csi.v1.Controller/DeleteVolume
[pod/csi-smb-controller-794dfcb554-sd6gc/smb] I0915 05:07:46.821498       1 utils.go:77] GRPC request: {"secrets":"***stripped***","volume_id":"smb-server.default.svc.cluster.local/share#smb-6446/pvc-t8w7t#pvc-537d3618-595b-4796-81f6-794effd6d54e#"}
[pod/csi-smb-controller-794dfcb554-sd6gc/smb] I0915 05:07:46.821684       1 controllerserver.go:169] DeleteVolume: found mountOptions(dir_mode=0777,file_mode=0777,uid=0,gid=0,mfsymlinks) for …
```
> fix: remove parent dir in DeleteVolume

- pkg/smb/controllerserver.go
/kind bug
fix: delete volume failure due to permission issue
Fixes #
```
fix: delete volume failure due to permission issue
```
> fix: delete volume failure due to permission issue

- .github/dependabot.yaml
/kind testing
Chores:remove group update rule
Fixes #
```
none
```
> Chores:remove group update rule

- test/e2e/dynamic_provisioning_test.go
- test/e2e/testsuites/dynamically_provisioned_delete_pod_tester.go
/kind feature
-  Add test coverage to avoid regression of https://github.com/kubernetes-csi/csi-driver-smb/issues/834 .
```console
$ go test -v -timeout=0 ./test/e2e -ginkgo.v -ginkgo.timeout=1h
...
2024/11/29 15:13:47 ===================================================
[AfterSuite] PASSED [6.902 seconds]
------------------------------
Ran 13 of 14 Specs in 398.356 seconds
SUCCESS! -- 13 Passed | 0 Failed | 0 Pending | 1 Skipped
You're using deprecated Ginkgo functionality:
=============================================
Support for custom reporters has been removed in V2.  Please read the documentation linked to below for Ginkgo's new behavior and for a migration path:
Learn more at: …
```
> test: add read-only subdir e2e test

- Makefile
- pkg/smb/nodeserver.go
- pkg/smb/nodeserver_test.go
- pkg/smb/smb.go
- pkg/smb/smb_test.go
/kind feature
feat: support base64password field in secret
Fixes #573
```
feat: support base64password field in secret
```
> feat: support base64password field in secret

- Makefile
- pkg/smb/nodeserver.go
- pkg/smb/nodeserver_test.go
- pkg/smb/smb.go
- pkg/smb/smb_test.go
Reverts kubernetes-csi/csi-driver-smb#906
> Revert "feat: support base64password field in secret"

- .github/workflows/trivy.yaml
- Makefile
test: fix trivy action failure due to CVE-2024-45336
Fixes #
```release-note
none
```
> test: fix trivy action failure due to CVE-2024-45336

- go.mod
- pkg/util/util.go
- pkg/util/util_test.go
- vendor/go.uber.org/goleak/.gitignore
- vendor/go.uber.org/goleak/.golangci.yml
- vendor/go.uber.org/goleak/CHANGELOG.md
- vendor/go.uber.org/goleak/LICENSE
- vendor/go.uber.org/goleak/Makefile
- vendor/go.uber.org/goleak/README.md
- vendor/go.uber.org/goleak/doc.go
- vendor/go.uber.org/goleak/internal/stack/doc.go
- vendor/go.uber.org/goleak/internal/stack/scan.go
- vendor/go.uber.org/goleak/internal/stack/stacks.go
- vendor/go.uber.org/goleak/leaks.go
- vendor/go.uber.org/goleak/options.go
- vendor/go.uber.org/goleak/testmain.go
- vendor/go.uber.org/goleak/tracestack_new.go
- vendor/modules.txt
/kind bug
fix: goroutine leak
```
The write operation to a channel in Go is blocking unless there is a receiver waiting for it, this means after WaitUntilTimeout exit, the goroutine will remain stuck at done <- true forever.
After changed to buffered channel, even if there is no receiver, done <- true can successfully write and continue.
```
Fixes #
<details>
```
~/go/src/github.com/kubernetes-csi/csi-driver-smb/pkg/util# go test
--- FAIL: TestWaitUntilTimeout (3.44s)
util_test.go:80: found unexpected goroutines:
[Goroutine 8 in state chan send, with github.com/kubernetes-csi/csi-driver-smb/pkg/util.WaitUntilTimeout.func1 on top of …
```
> fix: goroutine leak when timeout

- pkg/smb/nodeserver.go
- pkg/smb/nodeserver_test.go
- pkg/smb/smb_common_linux.go
- pkg/smb/smb_common_linux_test.go
If the password to SMB-server contained special characters (e.g. "foo,bar"), the mount failed. Now, when the password is passed to mount via "credentials=filename" option, then mount succeeds.
/kind bug
Fixes https://github.com/kubernetes-csi/csi-driver-smb/issues/507, https://github.com/kubernetes-csi/csi-driver-smb/issues/358, https://github.com/kubernetes-csi/csi-driver-smb/issues/573  
```
none
```
> fix: enable to use secrets with special characters
